branches:
  - master
  - main
  - next
  - '[0-9]+.[0-9]+.x'
  - next-major
  - name: alpha
    prerelease: true
  - name: beta
    prerelease: true
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - '@semantic-release/git'
  - 'semantic-release-npm-github-publish'
ci: false
dryRun: false
debug: false
extends: "semantic-release-npm-github-publish"
