branches:
  - master
  - main
  - next
  - '[0-9]+.[0-9]+.x'
  - next-major
  - name: alpha
    prerelease: true
  - name: beta
    prerelease: true
ci: false
dryRun: false
debug: false
extends: "semantic-release-npm-github-publish"
